### ISSUE TITLE
Requires documentation to set up Pushbot . . .

### ISSUE THREAD

**Issue by M33FT** [zzsj0928/luci-app-pushbot#20]
Hi . . .
Thanks for your very good app. It is really very practical.
I wanted to see if there is a document to be read that introduced 
the implementation of the Pushbot notification system using the Telegram Bot?
Because I do not know how to set the Pushbot notification system.

![112665896-2b164980-8e79-11eb-8c16-70bb0a1fb4ad](https://user-images.githubusercontent.com/63062740/129447846-e9c34a3e-fe94-4ebe-9def-3cd937618a2b.gif)

Thanks Bro ;-)

**Comment by zzsj0928** [comment]
Pushbot support several tunnels from different providers, for each doc you may need to have a look from its official website.
you can direct it with the link on each page of pushbot webui.
but since the webhooks providers are mostly from CN, so the docs are almost all in chinese, i don' know if you can read it.
it's a bit complex for me to complete so many docs for each mode, i may not spend time on it.

**Comment by M33FT** [comment]
@zzsj0928 
Thanks for the answer / you are right brother / now the issue became clear to me;-)
